### ISSUE TITLE
Support Debian 10

### ISSUE THREAD

**Issue by serge-salamanka-1pt** [jmadureira/netdata-cookbook#33]
Same changes should be applied as in #32

**Comment by jmadureira** [comment]
@serge-salamanka-1pt or @salsa-dev Can you confirm that the issue is fixed on the master branch before I release the cookbook?

I need some time to setup the environment to properly test these last changes.

**Comment by salsa-dev** [comment]
@jmadureira i confirm that the changes in PR were tested and actually almost in production in my infra.
i have tested them also with T.Kitchen in netdata cookbook but there some changes needed in .kitchen.yml:
```
provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept-no-persist
```

I will appreciate if you commit and fix those issues with testing the cookbook itself.
